import os

DISCORD_BOT_TOKEN = os.getenv('DISCORD_BOT_TOKEN')
DISCORD_GUILD_ID = int(os.getenv('DISCORD_GUILD_ID'))
DISCORD_SERVER_LOGS_ID = int(os.getenv('DISCORD_SERVER_LOGS_ID'))
DISCORD_BACKUP_LOGS_ID = int(os.getenv('DISCORD_BACKUP_LOGS_ID'))
SERVER_PORT = os.getenv('SERVER_PORT')
